### ISSUE TITLE
The returned XML does not match the expected schema. (code: PE233) 

### ISSUE THREAD

**Issue by josfdevasia** [greiginsydney/New-OoklaSpeedTest.ps1#8] opened 2023-04-10 10:37 UTC
Hi All,

When im trying this script in the sensor, im getting following error.
XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)
PowerShell remote execution policy has been enabled

**Comment by greiginsydney** [comment] 2023-04-10 23:24
Hi Josf(?),

Can you include a screen-grab, or include the command string you're sending to the script?

It might also be helpful if you re-run it with the "-debug" switch. This will dump a log file into the same directory, and this might help with debugging.

\- G.

**Comment by greiginsydney** [comment] 2023-04-10 23:26
Actually, this is probably a dupe of Bug #7 and Bug #4. Check out this link:
https://github.com/greiginsydney/New-OoklaSpeedTest.ps1/issues/4#issuecomment-745606893

\- Greig.

**Closed** 2023-04-19 04:35 UTC
